### ISSUE TITLE
sponsor() function in open to reentrancy attacks

### ISSUE THREAD

**Issue by code423n4** [code-423n4/2022-01-sandclock-findings#4]
# Handle

jayjonah8

# Vulnerability details

## Impact
In Vault.sol the sponsor() function does not have a reentrancy guard allowing an attacker to reenter the function because the depositors.mint() function has as callback to the msg.sender.  Since there are state updates after the call to depositors.mint() function this is especially dangerous.  An attacker can make it so the totalSponsored amount is only updated once after calling mint() several times since the update takes place after the callback.  The same will be true for the Sponsored event that is emitted. 

## Proof of Concept
https://github.com/code-423n4/2022-01-sandclock/blob/main/sandclock/contracts/Vault.sol#L244

## Tools Used
Manual code review 

## Recommended Mitigation Steps
A reentrancy guard modifier should be added to the sponsor() function in Vault.sol

**Comment by MrToph** [comment]
> An attacker can make it so the totalSponsored amount is only updated once after calling mint() several times since the update takes place after the callback. 

given the high severity, I would have liked to see how this can be used to steal funds or break functionality. attack path is not clear to me

**Comment by 0xEzSwim** [comment]
> > An attacker can make it so the totalSponsored amount is only updated once after calling mint() several times since the update takes place after the callback.
> 
> given the high severity, I would have liked to see how this can be used to steal funds or break functionality. attack path is not clear to me

You and me both haha. 

I wasn't able to find a way to steal funds while reentering the `Vault::sponsor()` either. From what I know, `Vault::sponsor()` never calls the `Vautl::underlying.balanceOf(address(this))` to update the storage (which ultimately was the issue with the `Vault::deposit()` call).

Furthermore, the attacker can't call `Vault::forceUnsponsor()` either from a malicious `Attacker::onERC721Received()` because of the time lock set on the sponsor's deposit. 

To me it's a false positive.
